// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {model} from '../models';
import {fingerprint} from '../models';
import {features} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function DownloadNuclei():Promise<desktop.NucleiStatus>;

export function FindingEvidence(arg1:string):Promise<Array<model.FindingEvidence>>;

export function GetAISettings():Promise<Record<string, any>>;

export function GetNucleiStatus():Promise<desktop.NucleiStatus>;

export function GetOOBDomain():Promise<string>;

export function ImportHFingerRule():Promise<fingerprint.HFingerStats>;

export function ReloadHFingerRules():Promise<fingerprint.HFingerStats>;

export function RuntimeLogs(arg1:number):Promise<Array<model.RuntimeLog>>;

export function SaveAISettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetCustomProbePaths(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedContentTypes(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedDomains(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedPaths(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedPostParameters(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedQueryParameters(arg1:Array<string>):Promise<Array<string>>;

export function SetExcludedSuffixes(arg1:Array<string>):Promise<Array<string>>;

export function SetFeature(arg1:string,arg2:boolean):Promise<Array<features.Definition>>;

export function SetNucleiBinaryPath(arg1:string):Promise<desktop.NucleiStatus>;

export function SetOOBDomain(arg1:string):Promise<void>;

export function SetPassiveFastjsonProbeQPS(arg1:number):Promise<void>;

export function SetPassiveFileProbeMaxPrefixes(arg1:number):Promise<void>;

export function SetPassiveFileProbeQPS(arg1:number):Promise<void>;

export function SetPassivePOCConcurrency(arg1:number):Promise<void>;

export function SetPassivePOCQPS(arg1:number):Promise<void>;

export function SetPassiveSQLiMaxParameters(arg1:number):Promise<void>;

export function SetPassiveSQLiMaxRequests(arg1:number):Promise<void>;

export function SetPassiveSQLiProbeQPS(arg1:number):Promise<void>;

export function SetPassiveShiroProbeQPS(arg1:number):Promise<void>;

export function SetPassiveXSSMaxParameters(arg1:number):Promise<void>;

export function SetPassiveXSSMaxRequests(arg1:number):Promise<void>;

export function SetPassiveXSSProbeQPS(arg1:number):Promise<void>;

export function SetSQLiTechniques(arg1:boolean,arg2:boolean,arg3:boolean):Promise<Array<features.Definition>>;

export function SetShiroKeys(arg1:Array<string>):Promise<void>;

export function SetSwaggerExcludedPaths(arg1:Array<string>):Promise<Array<string>>;

export function Snapshot():Promise<desktop.Snapshot>;

export function StartServices():Promise<desktop.Status>;

export function Status():Promise<desktop.Status>;

export function StopServices():Promise<desktop.Status>;

export function SubmitTask(arg1:desktop.TaskRequest):Promise<model.ActiveTask>;

export function TaskResults(arg1:string):Promise<Array<model.TaskResult>>;

export function WaitUntilStopped():Promise<void>;
