// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['desktop']['App']['CancelTask'](arg1);
}

export function DownloadNuclei() {
  return window['go']['desktop']['App']['DownloadNuclei']();
}

export function FindingEvidence(arg1) {
  return window['go']['desktop']['App']['FindingEvidence'](arg1);
}

export function GetAISettings() {
  return window['go']['desktop']['App']['GetAISettings']();
}

export function GetNucleiStatus() {
  return window['go']['desktop']['App']['GetNucleiStatus']();
}

export function GetOOBDomain() {
  return window['go']['desktop']['App']['GetOOBDomain']();
}

export function ImportHFingerRule() {
  return window['go']['desktop']['App']['ImportHFingerRule']();
}

export function ReloadHFingerRules() {
  return window['go']['desktop']['App']['ReloadHFingerRules']();
}

export function RuntimeLogs(arg1) {
  return window['go']['desktop']['App']['RuntimeLogs'](arg1);
}

export function SaveAISettings(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SaveAISettings'](arg1, arg2, arg3);
}

export function SetCustomProbePaths(arg1) {
  return window['go']['desktop']['App']['SetCustomProbePaths'](arg1);
}

export function SetExcludedContentTypes(arg1) {
  return window['go']['desktop']['App']['SetExcludedContentTypes'](arg1);
}

export function SetExcludedDomains(arg1) {
  return window['go']['desktop']['App']['SetExcludedDomains'](arg1);
}

export function SetExcludedPaths(arg1) {
  return window['go']['desktop']['App']['SetExcludedPaths'](arg1);
}

export function SetExcludedPostParameters(arg1) {
  return window['go']['desktop']['App']['SetExcludedPostParameters'](arg1);
}

export function SetExcludedQueryParameters(arg1) {
  return window['go']['desktop']['App']['SetExcludedQueryParameters'](arg1);
}

export function SetExcludedSuffixes(arg1) {
  return window['go']['desktop']['App']['SetExcludedSuffixes'](arg1);
}

export function SetFeature(arg1, arg2) {
  return window['go']['desktop']['App']['SetFeature'](arg1, arg2);
}

export function SetNucleiBinaryPath(arg1) {
  return window['go']['desktop']['App']['SetNucleiBinaryPath'](arg1);
}

export function SetOOBDomain(arg1) {
  return window['go']['desktop']['App']['SetOOBDomain'](arg1);
}

export function SetPassiveFastjsonProbeQPS(arg1) {
  return window['go']['desktop']['App']['SetPassiveFastjsonProbeQPS'](arg1);
}

export function SetPassiveFileProbeMaxPrefixes(arg1) {
  return window['go']['desktop']['App']['SetPassiveFileProbeMaxPrefixes'](arg1);
}

export function SetPassiveFileProbeQPS(arg1) {
  return window['go']['desktop']['App']['SetPassiveFileProbeQPS'](arg1);
}

export function SetPassivePOCConcurrency(arg1) {
  return window['go']['desktop']['App']['SetPassivePOCConcurrency'](arg1);
}

export function SetPassivePOCQPS(arg1) {
  return window['go']['desktop']['App']['SetPassivePOCQPS'](arg1);
}

export function SetPassiveSQLiMaxParameters(arg1) {
  return window['go']['desktop']['App']['SetPassiveSQLiMaxParameters'](arg1);
}

export function SetPassiveSQLiMaxRequests(arg1) {
  return window['go']['desktop']['App']['SetPassiveSQLiMaxRequests'](arg1);
}

export function SetPassiveSQLiProbeQPS(arg1) {
  return window['go']['desktop']['App']['SetPassiveSQLiProbeQPS'](arg1);
}

export function SetPassiveShiroProbeQPS(arg1) {
  return window['go']['desktop']['App']['SetPassiveShiroProbeQPS'](arg1);
}

export function SetPassiveXSSMaxParameters(arg1) {
  return window['go']['desktop']['App']['SetPassiveXSSMaxParameters'](arg1);
}

export function SetPassiveXSSMaxRequests(arg1) {
  return window['go']['desktop']['App']['SetPassiveXSSMaxRequests'](arg1);
}

export function SetPassiveXSSProbeQPS(arg1) {
  return window['go']['desktop']['App']['SetPassiveXSSProbeQPS'](arg1);
}

export function SetSQLiTechniques(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetSQLiTechniques'](arg1, arg2, arg3);
}

export function SetShiroKeys(arg1) {
  return window['go']['desktop']['App']['SetShiroKeys'](arg1);
}

export function SetSwaggerExcludedPaths(arg1) {
  return window['go']['desktop']['App']['SetSwaggerExcludedPaths'](arg1);
}

export function Snapshot() {
  return window['go']['desktop']['App']['Snapshot']();
}

export function StartServices() {
  return window['go']['desktop']['App']['StartServices']();
}

export function Status() {
  return window['go']['desktop']['App']['Status']();
}

export function StopServices() {
  return window['go']['desktop']['App']['StopServices']();
}

export function SubmitTask(arg1) {
  return window['go']['desktop']['App']['SubmitTask'](arg1);
}

export function TaskResults(arg1) {
  return window['go']['desktop']['App']['TaskResults'](arg1);
}

export function WaitUntilStopped() {
  return window['go']['desktop']['App']['WaitUntilStopped']();
}
